import React from "react";

export const ProductsMock=()=>{
let productsMock=[]
    return  productsMock=[{product:"Remera",size:"L",price:1500, brand:"Adidas", id:1,img:"https://www.mundodeportivo.com/files/content_image_mobile_filter/uploads/2022/03/21/62384e1d607c8.jpeg",description:"Remera Adidas desarrollada con la ultima tecnologia que abosorbe la transpiracion brindando una sensacion de frescura",category:"remeras"},
                            {product:"Pantalones",size:"M",price:1000, brand:"Zara", id:2,img:"https://denimrep.com/wp-content/uploads/2019/04/cropped-pantalones.jpg",description:"Jeans de tela ultra moderna que te permite sentirte comodo en cualquier circunstancia",category:"pantalones"},
                            {product:"Zapatilla",size:"L",price:3000, brand:"Foos", id:3,img:"https://solodeportes-9bvc3m9qgmf6g9x.stackpathdns.com/media/catalog/product/cache/7c4f9b393f0b8cb75f2b74fe5e9e52aa/z/a/zapatilla-john-foos-flashback-negra-305011641857001-1.jpg",description:"Calzado de ultima generacion especialmente diseñado para afrontar la vida post pandemia.",category:"calzados"},
                            {product:"Campera",size:"L",price:3000, brand:"Next", id:4,img:"https://scandinavian.com.ar/media/catalog/product/cache/84501bf2af75e659022a456946bd3e2c/w/s/ws_arctic_2x1_jkt_storm_4.jpg",description:"Campera ideal para climas extremos. Tela termica de tecnologia de avanzada..",category:"invierno"},
                            {product:"Buzo",size:"L",price:3000, brand:"Next", id:5,img:"https://www.kvnstatic.com/productos/64796573/g/64796573_1.jpg",description:"Buzo especialmente diseñado para ser una capa de proteccion que protega contra tempraturas bajas.",category:"invierno"},
                            {product:"Zapatilla",size:"L",price:3000, brand:"Foos", id:6,img:"https://solodeportes-9bvc3m9qgmf6g9x.stackpathdns.com/media/catalog/product/cache/7c4f9b393f0b8cb75f2b74fe5e9e52aa/z/a/zapatilla-john-foos-flashback-negra-305011641857001-1.jpg",description:"Calzado de ultima generacion especialmente diseñado para afrontar la vida post pandemia.",category:"calzados"},
                            {product:"Remera",size:"L",price:1500, brand:"Adidas", id:7,img:"https://www.mundodeportivo.com/files/content_image_mobile_filter/uploads/2022/03/21/62384e1d607c8.jpeg",description:"Remera Adidas desarrollada con la ultima tecnologia que abosorbe la transpiracion brindando una sensacion de frescura",category:"remeras"},
                            {product:"Remera",size:"L",price:1500, brand:"Adidas", id:8,img:"https://www.mundodeportivo.com/files/content_image_mobile_filter/uploads/2022/03/21/62384e1d607c8.jpeg",description:"Remera Adidas desarrollada con la ultima tecnologia que abosorbe la transpiracion brindando una sensacion de frescura",category:"remeras"},
                            {product:"Musculosa",size:"M",price:1000, brand:"Zara", id:9,img:"https://denimrep.com/wp-content/uploads/2019/04/cropped-pantalones.jpg",description:"Jeans de tela ultra moderna que te permite sentirte comodo en cualquier circunstancia",category:"pantalones"},]


  }